#pragma once
#include "FreeRTOS_interrupts.h"

void ResetISR() __attribute__ ((noreturn));
void NmiSR();
void FaultISR();

#define DEBUG_INTTABLE 0

#if DEBUG_INTTABLE
#define INT_DEFAULT_DECL(x) IntDefaultHandler_##x
#else
#define INT_DEFAULT_DECL(x) IntDefaultHandler
#endif

void INT_DEFAULT_DECL(00)();
void INT_DEFAULT_DECL(01)();
void INT_DEFAULT_DECL(02)();
void INT_DEFAULT_DECL(03)();
void INT_DEFAULT_DECL(04)();
void INT_DEFAULT_DECL(05)();
void INT_DEFAULT_DECL(06)();
void INT_DEFAULT_DECL(07)();
void INT_DEFAULT_DECL(08)();
void INT_DEFAULT_DECL(09)();
void INT_DEFAULT_DECL(10)();
void INT_DEFAULT_DECL(11)();
void INT_DEFAULT_DECL(12)();
void INT_DEFAULT_DECL(13)();
void INT_DEFAULT_DECL(14)();
void INT_DEFAULT_DECL(15)();
void INT_DEFAULT_DECL(16)();
void INT_DEFAULT_DECL(17)();
void INT_DEFAULT_DECL(18)();
void INT_DEFAULT_DECL(19)();
void INT_DEFAULT_DECL(20)();
void INT_DEFAULT_DECL(21)();
void INT_DEFAULT_DECL(22)();
void INT_DEFAULT_DECL(23)();
void INT_DEFAULT_DECL(24)();
void INT_DEFAULT_DECL(25)();
void INT_DEFAULT_DECL(26)();
void INT_DEFAULT_DECL(27)();
void INT_DEFAULT_DECL(28)();
void INT_DEFAULT_DECL(29)();
void INT_DEFAULT_DECL(30)();
void INT_DEFAULT_DECL(31)();
void INT_DEFAULT_DECL(32)();
void INT_DEFAULT_DECL(33)();
void INT_DEFAULT_DECL(34)();
void INT_DEFAULT_DECL(35)();
void INT_DEFAULT_DECL(36)();
void INT_DEFAULT_DECL(37)();
void INT_DEFAULT_DECL(38)();
void INT_DEFAULT_DECL(39)();
void INT_DEFAULT_DECL(40)();
void INT_DEFAULT_DECL(41)();
void INT_DEFAULT_DECL(42)();
void INT_DEFAULT_DECL(43)();
void INT_DEFAULT_DECL(44)();
void INT_DEFAULT_DECL(45)();
void INT_DEFAULT_DECL(46)();
void INT_DEFAULT_DECL(47)();
void INT_DEFAULT_DECL(48)();
void INT_DEFAULT_DECL(49)();
void INT_DEFAULT_DECL(50)();
void INT_DEFAULT_DECL(51)();
void INT_DEFAULT_DECL(52)();
void INT_DEFAULT_DECL(53)();
void INT_DEFAULT_DECL(54)();
void INT_DEFAULT_DECL(55)();
void INT_DEFAULT_DECL(56)();
void INT_DEFAULT_DECL(57)();
void INT_DEFAULT_DECL(58)();
void INT_DEFAULT_DECL(59)();
void INT_DEFAULT_DECL(60)();
void INT_DEFAULT_DECL(61)();
void INT_DEFAULT_DECL(62)();
void INT_DEFAULT_DECL(63)();
void INT_DEFAULT_DECL(64)();
void INT_DEFAULT_DECL(65)();
void INT_DEFAULT_DECL(66)();
void INT_DEFAULT_DECL(67)();
void INT_DEFAULT_DECL(68)();
void INT_DEFAULT_DECL(69)();
void INT_DEFAULT_DECL(70)();
void INT_DEFAULT_DECL(71)();
void INT_DEFAULT_DECL(72)();
void INT_DEFAULT_DECL(73)();
void INT_DEFAULT_DECL(74)();
void INT_DEFAULT_DECL(75)();
void INT_DEFAULT_DECL(76)();
void INT_DEFAULT_DECL(77)();
void INT_DEFAULT_DECL(78)();
void INT_DEFAULT_DECL(79)();